version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/html
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: install_nginx.sh
      timeout: 300
  ApplicationStart:
    - location: start_nginx.sh
      timeout: 300
