version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully.
      - echo Zipping the build directory...
      - zip -r build.zip build
      - echo Zipped build directory successfully.

artifacts:
  files:
    - build.zip

cache:
  paths:
    - 'node_modules/**/*'

