# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort
  selector:
    app: test
